# Generated by Django 6.0.5 on 2026-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='statut',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminé')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='kilometrage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='visite_technique',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('en_cours', 'En Cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='assurance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='etat',
            field=models.CharField(choices=[('active', 'Actif'), ('maintenance', 'En Maintenance'), ('inactive', 'Inactif'), ('disponible', 'Disponible'), ('en_mission', 'En Mission')], default='active', max_length=20),
        ),
    ]
