# Generated by Django 6.0.5 on 2026-06-03 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from datetime import date, timedelta, datetime

def migrate_existing_documents(apps, schema_editor):
    Vehicle = apps.get_model('core', 'Vehicle')
    VehicleDocument = apps.get_model('core', 'VehicleDocument')
    
    today = date.today()
    
    for vehicle in Vehicle.objects.all():
        # Migrate insurance
        if hasattr(vehicle, 'assurance') and vehicle.assurance:
            date_exp = today + timedelta(days=30)
            try:
                clean_date = vehicle.assurance.strip()
                parsed = datetime.strptime(clean_date[:10], '%Y-%m-%d').date()
                date_exp = parsed
            except Exception:
                pass
            
            VehicleDocument.objects.create(
                vehicle=vehicle,
                document_type='assurance',
                date_debut=date_exp - timedelta(days=365),
                date_expiration=date_exp,
                periode='1_an',
                statut='valide' if date_exp > today else 'expire',
                remarque="Importé de l'ancien champ Assurance"
            )
            
        # Migrate inspection (visite_technique)
        if hasattr(vehicle, 'visite_technique') and vehicle.visite_technique:
            date_exp = vehicle.visite_technique
            VehicleDocument.objects.create(
                vehicle=vehicle,
                document_type='visite_technique',
                date_debut=date_exp - timedelta(days=365),
                date_expiration=date_exp,
                periode='1_an',
                statut='valide' if date_exp > today else 'expire',
                remarque="Importé de l'ancien champ Visite Technique"
            )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chauffeur_statut_maintenance_statut_and_more'),
    ]

    operations = [
        # Rename Vehicule to Vehicle
        migrations.RenameModel(
            old_name='Vehicule',
            new_name='Vehicle',
        ),
        
        # Add type_vehicle field
        migrations.AddField(
            model_name='vehicle',
            name='type_vehicle',
            field=models.CharField(choices=[('tracteur', 'Tracteur'), ('remorque', 'Remorque')], default='tracteur', max_length=20),
        ),
        
        # Alter foreign keys to point to the new Vehicle model
        migrations.AlterField(
            model_name='carburant',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carburants', to='core.vehicle'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.vehicle'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.vehicle'),
        ),
        
        # Create VehicleDocument model
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('visite_technique', 'Visite technique'), ('carte_grise', 'Carte grise'), ('assurance', 'Assurance'), ('carte_bleue', 'Carte bleue'), ('licence_de_transport', 'Licence de transport'), ('taxe', 'Taxe')], max_length=50)),
                ('date_debut', models.DateField()),
                ('date_expiration', models.DateField()),
                ('periode', models.CharField(choices=[('3_mois', '3 mois'), ('6_mois', '6 mois'), ('1_an', '1 an')], max_length=20)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('expire_bientot', 'Expire bientôt'), ('expire', 'Expiré')], default='valide', max_length=20)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Document Véhicule',
                'verbose_name_plural': 'Documents Véhicule',
                'ordering': ['-date_expiration'],
            },
        ),
        
        # Migrate data from old assurance / visite_technique fields to new VehicleDocument
        migrations.RunPython(migrate_existing_documents),
        
        # Remove old fields
        migrations.RemoveField(
            model_name='vehicle',
            name='assurance',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='visite_technique',
        ),
        
        # Create RenewalHistory
        migrations.CreateModel(
            name='RenewalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_date_expiration', models.DateField()),
                ('nouvelle_date_expiration', models.DateField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='core.vehicledocument')),
            ],
            options={
                'verbose_name': 'Historique Renouvellement',
                'verbose_name_plural': 'Historiques Renouvellement',
                'ordering': ['-modified_at'],
            },
        ),
        
        # Create Notification
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.vehicle')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.vehicledocument')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
