# Generated by Django 6.0.5 on 2026-06-03 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehicle_alter_carburant_vehicule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=5)),
                ('prix_unitaire_moyen', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fournisseur_principal', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pièce de rechange',
                'verbose_name_plural': 'Pièces de rechange',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='maintenance',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to='maintenances/'),
        ),
        migrations.AddField(
            model_name='mission',
            name='heure_arrivee_prevue',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='heure_arrivee_reelle',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ControleRoutier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('agent_controle', models.CharField(max_length=200)),
                ('type_verification', models.CharField(max_length=300)),
                ('documents_verifies', models.TextField()),
                ('pieces_manquantes', models.JSONField(blank=True, default=list)),
                ('montant_amende', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('non_conforme', 'Non conforme')], default='conforme', max_length=20)),
                ('statut_amende', models.CharField(choices=[('non_payee', 'Non payée'), ('payee', 'Payée'), ('contestee', 'Contestée')], default='payee', max_length=20)),
                ('rapport', models.FileField(blank=True, null=True, upload_to='controles/')),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_routiers', to='core.chauffeur')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_routiers', to='core.mission')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_routiers', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Contrôle Routier',
                'verbose_name_plural': 'Contrôles Routiers',
                'ordering': ['-date', '-heure'],
            },
        ),
        migrations.CreateModel(
            name='Peage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_peage', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('moyen_paiement', models.CharField(max_length=50)),
                ('statut_paiement', models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente'), ('rembourse', 'Remboursé')], default='paye', max_length=20)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='peages/')),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peages', to='core.chauffeur')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peages', to='core.mission')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peages', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Péage',
                'verbose_name_plural': 'Péages',
                'ordering': ['-date', '-heure'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fournisseur', models.CharField(blank=True, max_length=200, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.maintenance')),
                ('spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisations', to='core.sparepart')),
            ],
            options={
                'verbose_name': 'Pièce utilisée',
                'verbose_name_plural': 'Pièces utilisées',
                'ordering': ['nom'],
            },
        ),
    ]
