# Generated by Django 6.0.5 on 2026-06-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sparepart_maintenance_facture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicledocument',
            options={'ordering': ['-date_expiration'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='notification',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.chauffeur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='renewalhistory',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.chauffeur'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='numero_document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='document_type',
            field=models.CharField(choices=[('visite_technique', 'Visite technique'), ('carte_grise', 'Carte grise'), ('assurance', 'Assurance'), ('carte_bleue', 'Carte bleue'), ('licence_de_transport', 'Licence de transport'), ('taxe', 'Taxe'), ('permis_de_conduire', 'Permis de conduire')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='periode',
            field=models.CharField(choices=[('3_mois', '3 mois'), ('6_mois', '6 mois'), ('1_an', '1 an'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.vehicle'),
        ),
    ]
